### ISSUE TITLE
Modify SetupPostEnvironment to remove add liquidity feature

### ISSUE THREAD

**Issue by daopunk** [open-dollar/od-relayer#43]
- Only the relayer should be initialized. 
- Remove pool creation (will be created manually using the app)
- Remove add liquidity

**Comment by daopunk** [comment]
@pi0neerpat can we close this issue since PR 41 actually solves initialization correctly

**Comment by pi0neerpat** [comment]
Please correct me if any of this are wrong. We decided to create the CamelotPool for mainnet using the app UI, therefore we do not need to run the SetupPostEnvironment script. Therefore we don't need to make any more changes to it? If thats true then yes we can close this.

I will make another issue to document better what is available in this repo, and the steps we expect to take in our spellbook

**Comment by pi0neerpat** [comment]
Not using script to deploy mainnet camelotpool
